<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pl74Lb1' shared service.

return $this->privates['.service_locator.pl74Lb1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commentRepository' => ['privates', 'App\\Repository\\Admin\\CommentRepository', 'getCommentRepositoryService.php', true],
], [
    'commentRepository' => 'App\\Repository\\Admin\\CommentRepository',
]);
