<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3J553_g' shared service.

return $this->privates['.service_locator.3J553_g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'shopcart' => ['privates', '.errored..service_locator.3J553_g.App\\Entity\\Shopcart', NULL, 'Cannot autowire service ".service_locator.3J553_g": it references class "App\\Entity\\Shopcart" but no such service exists.'],
], [
    'shopcart' => 'App\\Entity\\Shopcart',
]);
