<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bOGtNAj' shared service.

return $this->privates['.service_locator.bOGtNAj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'message' => ['privates', '.errored..service_locator.bOGtNAj.App\\Entity\\Admin\\Messages', NULL, 'Cannot autowire service ".service_locator.bOGtNAj": it references class "App\\Entity\\Admin\\Messages" but no such service exists.'],
], [
    'message' => 'App\\Entity\\Admin\\Messages',
]);
