<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.O0o6cgi' shared service.

return $this->privates['.service_locator.O0o6cgi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'settingRepository' => ['privates', 'App\\Repository\\SettingRepository', 'getSettingRepositoryService.php', true],
], [
    'settingRepository' => 'App\\Repository\\SettingRepository',
]);
