<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nkuMMzS' shared service.

return $this->privates['.service_locator.nkuMMzS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'setting' => ['privates', '.errored..service_locator.nkuMMzS.App\\Entity\\Setting', NULL, 'Cannot autowire service ".service_locator.nkuMMzS": it references class "App\\Entity\\Setting" but no such service exists.'],
], [
    'setting' => 'App\\Entity\\Setting',
]);
