<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.EpAI2BG' shared service.

return $this->privates['.service_locator.EpAI2BG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commentRepository' => ['privates', 'App\\Repository\\Admin\\CommentRepository', 'getCommentRepositoryService.php', true],
    'imageRepository' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService.php', true],
    'product' => ['privates', '.errored..service_locator.EpAI2BG.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.EpAI2BG": it references class "App\\Entity\\Product" but no such service exists.'],
], [
    'commentRepository' => 'App\\Repository\\Admin\\CommentRepository',
    'imageRepository' => 'App\\Repository\\ImageRepository',
    'product' => 'App\\Entity\\Product',
]);
