<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.3J553_g.App\Entity\Shopcart' shared service.

include_once $this->targetDirs[3].'/src/Entity/Shopcart.php';

return $this->privates['.errored..service_locator.3J553_g.App\\Entity\\Shopcart'] = new \App\Entity\Shopcart();
