<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHKHMNxx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHKHMNxx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHKHMNxx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHKHMNxx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHKHMNxx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HKHMNxx',
    'container.build_id' => '429404c0',
    'container.build_time' => 1652266301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHKHMNxx');
